#!/bin/bash

SDKDIR="$( dirname "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" )"

function copy_skeleton {
    cp -r $SDKDIR/share/eosiocontract/skeleton .
    echo "TODO: renaming step"
}

function build_contract {
    echo "TODO: build $1"
}

function print_help {
    echo "Usage: $0 contract.cpp"
    echo "       OR"
    echo "       $0 -n mycontract"
    echo
    echo "Options:"
    echo "   -n | --newcontract [name]"
    echo "      Create a new contract in the [name] folder, based on the example contract"
}

echo Using SDK at $SDKDIR

OPTIONS=$(getopt --options=hn: --longoptions=help,newcontract: --name "$0" -- "$@")
if [[ $? -ne 0 ]]; then
    # getopt failed
    exit 2
fi

eval set -- "$OPTIONS"

while true; do
    case "$1" in
        -n|--newcontract)
            newname=$2
            shift 2
            ;;
        -h|--help)
            print_help
            exit 1
            ;;
        --)
            shift
            break
            ;;
        *)
            echo "Unrecognized option: $1"
            exit 1
            ;;
    esac
done

if [[ "x" == "x$newname" ]]; then
    if [[ $# -ne 1 ]]; then
        print_help
        exit 1
    fi
    build_contract $1
else
    if [[ $# -ne 0 ]]; then
        print_help
        exit 1
    fi
    copy_skeleton $newname
fi
